### PR TITLE
Make lambdaFile argument to bst-proxy command optional

### PR DESCRIPTION
**Pull request by breathe**
I would like to invoke command from serverless-plugin-bespoken without arguments -- here's attempt to make lambdaFile argument to bst-proxy command optional.

### CODE REVIEW

**Comment by jperata** [comment]
@breathe Right now serverless plugin works without parameters, but a little different that what it's setup here. Right now it checks the serverless context for the declared handlers and functions and take the first one.

**Comment by breathe** [comment]
I'm working toward submitting a PR to serverless-plugin-bespoken to do a couple of things:

(1) add a 'deploy-passthru' command that will deploy a pass-thru version of specified lambdas -- with pass-thru lambda configured to forward request handling through the bespoken proxy for invocation on the developer machine
(2) launch the lambda proxy without arguments (will use url parameter from request to find the correct lambda to invoke which would work well with the deploy-passthru mechanism)
(3) change the proxy invocation mechanism to launch the lambda proxy server in process rather than in a subprocess (for best debugger ergonomics)

(3) might require another PR to bst ... but that's where I was headed with this change ...  These changes would provide a straightforward(ish) way to put breakpoints in lambda's that are invoked from arbitrary external event sources.

**Comment by jkelvie** [comment]
@breathe, my comments are inline:
1) Yes, makes sense per our earlier discussions
2) This is something is generally useful - I think we should add instructions/info to the console output to explain to people how to use it without specifying a lambda
3) I also think this makes sense, and what I was wondering about when I saw this
Though using the proxy without specifying a lambda makes sense, I believe for the serverless plugin it is better for it to be launched via a direct call to the BSTProxy class as opposed to invoking the command-line.

It sounds like this is what you had in mind as well - am I understanding correctly?

**Comment by breathe** [comment]
@jkelvie yeah I think we're on the same page.  

I may have been pre-mature to propose a change to the CLI above -- I was thinking to first make the changes to serverless-plugin-bespoken using the existing out of process proxy server mechanism -- and then figure out the right place to change things so that the same effect could be achieved in process.  

Earlier I had hacked together something that would launch the proxy server in process -- but it was basically duplicating code from the CLI  and I believe I had to add additional exports to BST -- I think I needed access to all of these 

```import { BSTProxy, URLMangler, Global, LoggingHelper } from "bespoken-tools"```

I'm guessing it's probably better to add the needed code to bst somewhere.  I thought a good path to get there would be to update the serverless-plugin-bespoken to first add the deploy-passthru command and keep using the existing CLI -- and then after that to ask after how best to export something from bst that provided the ability to launch the proxy server in process ...?

**Comment by jkelvie** [comment]
The BSTProxy should do what you are describing, though it still requires a file as an argument.

Starting an instance of the proxy and the Lambda service is done via a call like this:
```
const proxy = BSTProxy.lambda("index.js", 10001).secretKey("<KEY>").start(() => {
    console.log("Proxy started!");
});
```

More details are here:
http://docs.bespoken.io/en/latest/api/classes/bstproxy.html

A previous version did require that some global configuration happen before, but we resolved this recently:
https://github.com/bespoken/bst/pull/318/files

As of version 1.0.2, the only requirement to use it should be the BSTProxy import itself. 

I am open to an approach that still use the CLI - I'm not sure how that can be done in the same process though. Hopefully, the programmatic use of BSTProxy works for you. If it does not, let me know and we can figure out what the problem is with it (I just tested it, and it is working okay for me).

**Comment by breathe** [comment]
Ah excellent!  I didn't know about these changes!

What is the thinking around the handling of the secretKey?  Not sure about other use cases -- but it seems like the 'right' thing to do from within the serverless-plugin-bespoken would be to use the secretKey from ~/.bst/config -- is there a way I can get that behavior from within serverless-plugin-bespoken without duplicating code or importing Global object?

**Comment by jkelvie** [comment]
That's a great point with regard to the secretKey - that is one of the things that was getting loaded with Global.initialize() call that we took out.

In the current form, I believe it will be necessary to call Global.loadConfig to ensure everything gets initialized the first time, something like this:
```
Global.loadConfig().then(() => {
    bst.BSTProxy.lambda("index.js").secretKey("<KEY>").start(() =>{
        console.log("Started");
    });
});
```

Without that call, things may not work correctly for users that are just getting setup.

Which makes me think @jperata - should we just change this condition:
https://github.com/bespoken/bst/blob/7701d87e3dc07554f4c7d2c1123667a31ec7d90f/lib/client/bst-proxy.ts#L138

So that if the secret key is not set, it will go ahead and load the config?

The path that bypasses loading the configuration really only helps "power users". For everyone else, it would be better to just call `loadConfig`.

With that change, it would also remove the need for the client to call loadConfig (and exposing Global, which I would strongly prefer not to do), as in the sample code above.

I don't see a downside to this approach.

**Pull request merged**
